import { randomInt } from "node:crypto";

import { and, asc, count, desc, eq, ne, sql } from "drizzle-orm";
import { alias } from "drizzle-orm/pg-core";

import { INVITE_CODE_ALPHABET, INVITE_CODE_LENGTH } from "#lib/group-fields.ts";
import {
  type Action,
  type ActionOutcome,
  runAction,
} from "#lib/server/actions.ts";
import type { Db, Transaction } from "#lib/server/db/client.ts";
import {
  groupMembers,
  groups,
  inviteLookupLimits,
} from "#lib/server/db/schema.ts";

// The only module that changes groups and their members. Every change is an
// action (applied at most once per action ID, see actions.ts) and starts by
// locking the group's row, so changes to one group run one at a time: two
// joins can't both take the last place, and a leave can't race a delete.
//
// Callers pass inputs that already passed #lib/group-fields.ts; this module
// checks permissions, which depend on the database.

/** Hidden safety limit against a leaked invite; the app doesn't show it. */
export const MAX_GROUP_MEMBERS = 100;

// Lookups per user per window, counting previews and joins. Generous for
// people opening a few links, far too few to guess one of ~890M codes.
export const MAX_INVITE_LOOKUPS = 20;
export const LOOKUP_WINDOW_MINUTES = 10;

/**
 * Why a change was refused (nothing changed, nothing was logged):
 * - `not_found`: no such group, or you aren't in it. One answer for both, so
 *   non-members can't tell whether a group exists.
 * - `not_owner`: only the owner can do this.
 * - `nickname_taken`: someone in the group already uses it (ignoring case).
 * - `group_full`: the group has MAX_GROUP_MEMBERS members.
 * - `invite_invalid`: the code isn't this group's (wrong, or reset).
 * - `too_many_lookups`: over the invite lookup limit; try again later.
 * - `cannot_remove_self`: the owner leaves instead of removing themselves.
 */
export type GroupRefusal =
  | "not_found"
  | "not_owner"
  | "nickname_taken"
  | "group_full"
  | "invite_invalid"
  | "too_many_lookups"
  | "cannot_remove_self";

export type GroupOutcome = ActionOutcome | GroupRefusal;

// Thrown inside a transaction to roll it back, action log entry included, so
// a retry after fixing the problem (say, a new nickname) runs normally.
class Refusal extends Error {
  constructor(readonly reason: GroupRefusal | "conflict") {
    super(reason);
  }
}

async function runGroupAction(
  db: Db,
  action: Action,
  apply: (tx: Transaction) => Promise<void>
): Promise<GroupOutcome> {
  try {
    return await runAction(db, action, apply);
  } catch (error) {
    if (error instanceof Refusal) return error.reason;
    throw error;
  }
}

// ---------------------------------------------------------------------------
// Changes

interface Change {
  /** Generated by the browser, so a retried request carries the same ID. */
  actionId: string;
  /** The acting user, from the login session. */
  userId: string;
}

interface GroupChange extends Change {
  groupId: string;
}

/**
 * Creates a group with the user as its owner. The browser picks the group's
 * ID, so a retry of a create that went through finds the same group.
 */
export function createGroup(
  db: Db,
  change: GroupChange & { name: string; nickname: string }
): Promise<GroupOutcome> {
  const { actionId, userId, groupId, name, nickname } = change;
  const action: Action = {
    id: actionId,
    userId,
    type: "group_create",
    groupId,
    groupName: name,
    nickname,
  };
  return runGroupAction(db, action, async (tx) => {
    const created = await tx
      .insert(groups)
      .values({ id: groupId, name, inviteCode: newInviteCode() })
      .onConflictDoNothing({ target: groups.id })
      .returning({ id: groups.id });
    // Another action already created a group with this ID: a bug or a
    // tampered request, never a retry (that would share the action ID).
    if (created.length === 0) throw new Refusal("conflict");
    await tx.insert(groupMembers).values({
      groupId,
      userId,
      role: "owner",
      nickname,
    });
  });
}

/**
 * Joins a group with its invite code. The join page sends the group's ID
 * from its preview (previewInvite) along with the code, and the code must
 * still belong to that group. Already a member: nothing changes, and the
 * outcome is still `applied` (you're in the group).
 */
export async function joinGroup(
  db: Db,
  change: GroupChange & { inviteCode: string; nickname: string }
): Promise<GroupOutcome> {
  const { actionId, userId, groupId, inviteCode, nickname } = change;
  // A retry of a join that already went through (its response was lost)
  // must reach runAction to be recognized, even at the lookup limit. An ID
  // in the log is never a new guess: runAction answers it without looking
  // at the code.
  const logged = await db.query.actions.findFirst({
    columns: { id: true },
    where: { id: actionId },
  });
  // Counted even with the group's ID in hand: a removed member knows it and
  // could otherwise guess at the new code without limit.
  if (logged === undefined && !(await consumeInviteLookup(db, userId))) {
    return "too_many_lookups";
  }

  const action: Action = {
    id: actionId,
    userId,
    type: "group_join",
    groupId,
    nickname,
  };
  return runGroupAction(db, action, async (tx) => {
    // A missing group and a wrong or reset code look the same to the joiner.
    const [locked] = await tx
      .select({ inviteCode: groups.inviteCode })
      .from(groups)
      .where(eq(groups.id, groupId))
      .for("update");
    if (locked?.inviteCode !== inviteCode) {
      throw new Refusal("invite_invalid");
    }
    if ((await findMembership(tx, groupId, userId)) !== undefined) return;

    const [members] = await tx
      .select({ n: count() })
      .from(groupMembers)
      .where(eq(groupMembers.groupId, groupId));
    if ((members?.n ?? 0) >= MAX_GROUP_MEMBERS) {
      throw new Refusal("group_full");
    }
    await requireFreeNickname(tx, groupId, nickname, userId);
    await tx
      .insert(groupMembers)
      .values({ groupId, userId, role: "member", nickname });
  });
}

/**
 * Leaves the group. An owner who leaves hands ownership to the
 * longest-standing member; the last member to leave deletes the group.
 */
export function leaveGroup(db: Db, change: GroupChange): Promise<GroupOutcome> {
  const { actionId, userId, groupId } = change;
  const action: Action = { id: actionId, userId, type: "group_leave", groupId };
  return runGroupAction(db, action, async (tx) => {
    const me = await requireMember(tx, groupId, userId);
    await tx
      .delete(groupMembers)
      .where(
        and(eq(groupMembers.groupId, groupId), eq(groupMembers.userId, userId))
      );

    const [next] = await tx
      .select({ userId: groupMembers.userId })
      .from(groupMembers)
      .where(eq(groupMembers.groupId, groupId))
      // The user ID only breaks exact ties, so the choice never depends on
      // which row Postgres happens to read first.
      .orderBy(asc(groupMembers.joinedAt), asc(groupMembers.userId))
      .limit(1);
    if (next === undefined) {
      await tx.delete(groups).where(eq(groups.id, groupId));
    } else if (me.role === "owner") {
      await tx
        .update(groupMembers)
        .set({ role: "owner" })
        .where(
          and(
            eq(groupMembers.groupId, groupId),
            eq(groupMembers.userId, next.userId)
          )
        );
    }
  });
}

/** Owner only. Already gone (say, they left): nothing changes. */
export function removeMember(
  db: Db,
  change: GroupChange & { memberId: string }
): Promise<GroupOutcome> {
  const { actionId, userId, groupId, memberId } = change;
  const action: Action = {
    id: actionId,
    userId,
    type: "group_remove_member",
    groupId,
    memberId,
  };
  return runGroupAction(db, action, async (tx) => {
    await requireOwner(tx, groupId, userId);
    if (memberId === userId) throw new Refusal("cannot_remove_self");
    await tx
      .delete(groupMembers)
      .where(
        and(
          eq(groupMembers.groupId, groupId),
          eq(groupMembers.userId, memberId)
        )
      );
  });
}

/** Owner only. */
export function renameGroup(
  db: Db,
  change: GroupChange & { name: string }
): Promise<GroupOutcome> {
  const { actionId, userId, groupId, name } = change;
  const action: Action = {
    id: actionId,
    userId,
    type: "group_rename",
    groupId,
    groupName: name,
  };
  return runGroupAction(db, action, async (tx) => {
    await requireOwner(tx, groupId, userId);
    await tx.update(groups).set({ name }).where(eq(groups.id, groupId));
  });
}

/** Owner only. Members go with it (foreign key cascade). */
export function deleteGroup(
  db: Db,
  change: GroupChange
): Promise<GroupOutcome> {
  const { actionId, userId, groupId } = change;
  const action: Action = {
    id: actionId,
    userId,
    type: "group_delete",
    groupId,
  };
  return runGroupAction(db, action, async (tx) => {
    await requireOwner(tx, groupId, userId);
    await tx.delete(groups).where(eq(groups.id, groupId));
  });
}

/** Owner only. Replaces the invite code; the old one stops working. */
export function resetInvite(
  db: Db,
  change: GroupChange
): Promise<GroupOutcome> {
  const { actionId, userId, groupId } = change;
  const action: Action = {
    id: actionId,
    userId,
    type: "group_reset_invite",
    groupId,
  };
  return runGroupAction(db, action, async (tx) => {
    await requireOwner(tx, groupId, userId);
    await tx
      .update(groups)
      .set({ inviteCode: newInviteCode() })
      .where(eq(groups.id, groupId));
  });
}

/** Changes what this group calls you. */
export function setNickname(
  db: Db,
  change: GroupChange & { nickname: string }
): Promise<GroupOutcome> {
  const { actionId, userId, groupId, nickname } = change;
  const action: Action = {
    id: actionId,
    userId,
    type: "group_set_nickname",
    groupId,
    nickname,
  };
  return runGroupAction(db, action, async (tx) => {
    await requireMember(tx, groupId, userId);
    await requireFreeNickname(tx, groupId, nickname, userId);
    await tx
      .update(groupMembers)
      .set({ nickname })
      .where(
        and(eq(groupMembers.groupId, groupId), eq(groupMembers.userId, userId))
      );
  });
}

// ---------------------------------------------------------------------------
// Reads

/** The user's groups, alphabetically, with member counts. */
export function listGroups(db: Db, userId: string) {
  // The outer query reads the user's own membership row; this counts all of
  // the group's rows, so it needs its own name for the same table.
  const everyone = alias(groupMembers, "everyone");
  const memberCount = db
    .select({ n: count() })
    .from(everyone)
    .where(eq(everyone.groupId, groups.id));
  return db
    .select({
      id: groups.id,
      name: groups.name,
      role: groupMembers.role,
      memberCount: sql<number>`(${memberCount})`.mapWith(Number),
    })
    .from(groupMembers)
    .innerJoin(groups, eq(groups.id, groupMembers.groupId))
    .where(eq(groupMembers.userId, userId))
    .orderBy(asc(sql`lower(${groups.name})`), asc(groups.id));
}

/**
 * The group as one of its members sees it, or null when the user isn't a
 * member (or it doesn't exist): pages answer both with the same 404.
 */
export async function getGroupForMember(
  db: Db,
  groupId: string,
  userId: string
) {
  const group = await db.query.groups.findFirst({
    columns: { id: true, name: true, inviteCode: true },
    where: { id: groupId },
    with: {
      members: {
        columns: { userId: true, nickname: true, role: true },
        orderBy: { joinedAt: "asc", userId: "asc" },
      },
    },
  });
  const me = group?.members.find((member) => member.userId === userId);
  if (group === undefined || me === undefined) return null;
  return { ...group, me };
}

/**
 * The group behind an invite code, for the "Join this group?" page. Counts
 * against the same lookup limit as joining, or the preview would be a free
 * way to guess codes.
 */
export async function previewInvite(
  db: Db,
  userId: string,
  inviteCode: string
): Promise<
  | { status: "found"; id: string; name: string; isMember: boolean }
  | { status: "invite_invalid" | "too_many_lookups" }
> {
  if (!(await consumeInviteLookup(db, userId))) {
    return { status: "too_many_lookups" };
  }
  const group = await db.query.groups.findFirst({
    columns: { id: true, name: true },
    where: { inviteCode },
    with: { members: { columns: { userId: true }, where: { userId } } },
  });
  if (group === undefined) return { status: "invite_invalid" };
  return {
    status: "found",
    id: group.id,
    name: group.name,
    isMember: group.members.length > 0,
  };
}

/** The nickname from the user's most recent join, to prefill the next one. */
export async function lastNickname(db: Db, userId: string): Promise<string> {
  const [row] = await db
    .select({ nickname: groupMembers.nickname })
    .from(groupMembers)
    .where(eq(groupMembers.userId, userId))
    .orderBy(desc(groupMembers.joinedAt))
    .limit(1);
  return row?.nickname ?? "";
}

// ---------------------------------------------------------------------------
// Helpers

/**
 * Locks the group's row until the transaction ends. Every membership change
 * takes this lock first, so changes to one group queue instead of racing.
 */
async function lockGroup(tx: Transaction, groupId: string): Promise<void> {
  const [group] = await tx
    .select({ id: groups.id })
    .from(groups)
    .where(eq(groups.id, groupId))
    .for("update");
  if (group === undefined) throw new Refusal("not_found");
}

function findMembership(tx: Transaction, groupId: string, userId: string) {
  return tx.query.groupMembers.findFirst({
    columns: { role: true },
    where: { groupId, userId },
  });
}

async function requireMember(tx: Transaction, groupId: string, userId: string) {
  await lockGroup(tx, groupId);
  const membership = await findMembership(tx, groupId, userId);
  if (membership === undefined) throw new Refusal("not_found");
  return membership;
}

async function requireOwner(tx: Transaction, groupId: string, userId: string) {
  const membership = await requireMember(tx, groupId, userId);
  if (membership.role !== "owner") throw new Refusal("not_owner");
}

// Checked under the group lock, so it's reliable; the unique index on
// (group, lower(nickname)) backs it up.
async function requireFreeNickname(
  tx: Transaction,
  groupId: string,
  nickname: string,
  userId: string
): Promise<void> {
  const [taken] = await tx
    .select({ userId: groupMembers.userId })
    .from(groupMembers)
    .where(
      and(
        eq(groupMembers.groupId, groupId),
        eq(sql`lower(${groupMembers.nickname})`, sql`lower(${nickname})`),
        ne(groupMembers.userId, userId)
      )
    )
    .limit(1);
  if (taken !== undefined) throw new Refusal("nickname_taken");
}

// A collision with another group's code fails the request (unique index)
// rather than sharing a code; at ~890M codes, retrying is the cheaper fix.
function newInviteCode(): string {
  return Array.from(
    { length: INVITE_CODE_LENGTH },
    () => INVITE_CODE_ALPHABET[randomInt(INVITE_CODE_ALPHABET.length)]
  ).join("");
}

/**
 * Records one invite lookup and reports whether it's within the limit. One
 * atomic statement, like #lib/server/sign-in-code-limit.ts: concurrent
 * lookups queue on the row lock, so a burst can't slip past the count.
 */
async function consumeInviteLookup(db: Db, userId: string): Promise<boolean> {
  const { count: lookups, windowStartedAt } = inviteLookupLimits;
  const windowOver = sql`${windowStartedAt} < now() - make_interval(mins => ${LOOKUP_WINDOW_MINUTES})`;
  const [row] = await db
    .insert(inviteLookupLimits)
    .values({ userId, windowStartedAt: sql`now()`, count: 1 })
    .onConflictDoUpdate({
      target: inviteLookupLimits.userId,
      set: {
        count: sql`case when ${windowOver} then 1 else ${lookups} + 1 end`,
        windowStartedAt: sql`case when ${windowOver} then now() else ${windowStartedAt} end`,
      },
    })
    .returning({ count: lookups });
  return row !== undefined && row.count <= MAX_INVITE_LOOKUPS;
}
