import { redirect } from "@sveltejs/kit";
import { z } from "zod";

import { groupNameSchema, nicknameSchema } from "#lib/group-fields.ts";
import { db } from "#lib/server/db/index.ts";
import { readForm, refusal } from "#lib/server/group-forms.ts";
import { createGroup, lastNickname } from "#lib/server/groups.ts";
import { requireUser } from "#lib/server/require-user.ts";

import type { Actions, PageServerLoad } from "./$types";

export const load: PageServerLoad = async ({ locals }) => {
  const user = requireUser(locals);
  return { nickname: await lastNickname(db, user.id) };
};

const createSchema = z.object({
  actionId: z.uuid(),
  // Generated by the browser with the action ID (see ActionForm's newIds).
  groupId: z.uuid(),
  name: groupNameSchema,
  nickname: nicknameSchema,
});

export const actions = {
  default: async ({ request, locals }) => {
    const user = requireUser(locals);
    const form = await readForm(request, createSchema);
    if (!form.ok) return form.failure;

    const failed = refusal(
      await createGroup(db, { userId: user.id, ...form.data })
    );
    if (failed !== null) return failed;
    redirect(303, `/groups/${form.data.groupId}`);
  },
} satisfies Actions;
